### ISSUE TITLE
Compiling error windows qt (CTxDB

### ISSUE THREAD

**Issue by Crazyhead90** [carsenk/denarius#128]
I havent found a "official" guide to compile the windows qt for this project, but when i try to compile the denarius wallet for windows with random guides i find on the internet, i keep running into this error, what can i do to fix this and make it compile correctly?

![afbeelding](https://user-images.githubusercontent.com/20604229/40277698-fb818c1e-5c23-11e8-8c8d-6c0a5d204641.png)

**Comment by carsenk** [comment]
We don't support compiling on Windows, we always release official binaries for Windows, so you shouldn't need to compile it yourself. Typically if you are getting an error you are probably missing deps. This also seems like an error previous of v2.5 what version are you trying to compile?

**Comment by Crazyhead90** [comment]
I downloaded the master branch and tried to compile that, thats normally the most recent stable release right?

**Comment by enkayz** [comment]
Using BDB for the transaction database is not currently supported for standard compilation; only LevelDB is supported. The QT5 project file should be using `txdb-leveldb.cpp` by default. 

This error occurs because the `WriteAddrIndex` function is not currently implemented in `txdb-bdb.cpp` however it is implemented in `txdb-leveldb.cpp` which is included in default in the QT5 project and linux makefiles.

Currently if you are attempting to compile a headless windows daemon using makefile.mingw without specifying the environment parameter `USE_LEVELDB=1` then `txdb-bdb.cpp` will be compiled instead resulting in the `CTxDB` class not including the required `WriteAddrIndex` function.

We will update the makefiles in question to use leveldb by default in a later release, however for now the `USE_LEVELDB=1` environment variable should fix this issue for your compilation (assuming you are attempting a headless compile).

FWIW, I wouldn't recommend running a headless daemon on Windows; the overhead for GUI is minimal and it supports all functionality of the headless daemon, including the ability to run as a service (under your user account). You can use the 'Minimize to tray instead of taskbar' and 'Minimize on close' options to minimize (pun intended) the impact of running the GUI to a simple system tray icon.

**Comment by Crazyhead90** [comment]
I got it working, thanks
