### ISSUE TITLE
"Generik.GZPYLVZ" was found in a file that DenariusInstaller.exe tried to access. Virus Threat detected by ESET NOD32

### ISSUE THREAD

**Issue by digibytesalesman** [carsenk/denarius#25]
Dev Team,

Have you wondered why this Coin isnt Mooning-- Windows 10 users are getting virus notifications when trying to download the Core QT Desktop wallet for Denarius.

Is there a fix for this? A lot of people cannot Stake because of this... fix plz

**Comment by carsenk** [comment]
Simply add an exception for Denarius.exe in your anti-virus software. That should solve your issue. It is clean, but it is falsely flagged by anti-virus because it includes code that uses IRC to connect nodes, so its falsely flagged generally as an IRC bot. This method of connection may be removed in the future, to help minimize these types of incidents.

**Comment by digibytesalesman** [comment]
I disabled ESET and the Denarius QT Core works. You should really contact ESET Antivirus about this program and tell them to fix their false positive.

**Comment by digibytesalesman** [comment]
Thanks Carsenk !!

**Comment by gregpassmore** [comment]
FWIW I can't get Denarius to install because i can't get windows defender to exclude it since it thinks it has a virus. It won't let me add it to the exclusion list.

**Comment by inliquid** [comment]
My Windows Defender never said a word (Win10).

**Comment by gregpassmore** [comment]
![screenshot 2018-01-31 13 37 43](https://user-images.githubusercontent.com/2468045/35648886-12d32d7a-068c-11e8-815a-9c7a3d8a5e29.png)

**Comment by carsenk** [comment]
Just click okay, you want to go into your actual exclusions and select the .exe manually to be excluded. Most cryptocurrencies are falsely flagged due to the decentralized nature of the coin, it utilizes many different ports and connections, which can cause anti-virus to freak out a bit. We did remove the IRC connection code for future releases, so this should help some with the false flaggings.
