### ISSUE TITLE
Timestamps in logs do not reflect timezone

### ISSUE THREAD

**Issue by inliquid** [carsenk/denarius#92]
When
`logtimestamps=1` is set in _denarius.conf_, timestamps are provided in GMT with no respect to system timezone.

**Comment by carsenk** [comment]
This is not a bug. Timestamps are suppose to show in GMT.

**Comment by inliquid** [comment]
I never seen a system with GMT timestamps supposed to be a feature. It's for sure **a bug** and/or needs improvement. It's quite simple change over the code to just reject it. In other places, f,i. in QT you'll see real dates with correct time display. This bug makes harder to test anything.

**Comment by carsenk** [comment]
Well you can simply convert your GMT timestamps to your local time, this is not an issue or bug, we utilize GMT time-stamping and Unix Epochs (GMT/UTC). GMT is still widely used as the standard time against which all the other time zones in the world are referenced.

**Comment by enkayz** [comment]
i wouldn't consider this technically a bug - the debug file is typically raw information and since the blockchain is based on UTC time the debugging is not converted to local time, unlike in the QT display where most displayed times in the UI are converted to local time.

that being said, we can put an option to display the log timestamps in local time, if that would be useful to you, drop in a feature request and we'll progress it from there

**Comment by inliquid** [comment]
Call this whatever you like, it's called "issue" here on github. But suggestion to estimate correct timestamps in my mind when I'm using computer is a joke.

**Comment by enkayz** [comment]
the timestamps in question are displayed only in the debugging log file, which is intended to be used when debugging an issue with the operation of the code. in this case, if we ask a reporter for debug logs, the logs will be provided in a UTC time zone, standard locale, regardless of the user's system locale settings or timezone.

for this reason we don't believe that displaying the log timestamps in the system default timezone is a wise idea, however we are open to adding a feature that will enable a user to timestamp their debug logs using the system time in order to make it easier for them to read their own debug logs
