### ISSUE TITLE
[2.0] Synchronization speed drop

### ISSUE THREAD

**Issue by inliquid** [carsenk/denarius#94]
Synchronization speed has been dropped significantly (~10 times) with 2.0 release comparing to 1.0.7. It is way too slow. For example it synchronizes > **40-50 hours** comparing to **4-6 hours** with 1.0.7 [16 active connections 100mbps internet with ~92-95mbps up/down throughput test with speedtest.net].

**Comment by carsenk** [comment]
Nothing with syncing was changed in the newest version. We are looking into new methods to sync the client faster. The chain is just much larger than our previous releases, as we are around block 600k+ currently.

**Comment by inliquid** [comment]
I don't believe I can see dev comments like this. Carsen, are you ok? Synchronization speed has dropped **10 times**!

**Comment by enkayz** [comment]
in this case I believe the slowdown is situational and not related to the sync code, there are many factors that contribute to sync time, including but not limited to disk IO, CPU core performance, data reliability from currently selected nodes, latency and existing chain.

we do know the sync time from 0 blocks to current height is quite high (however nowhere near as high as other coins) so we are working on improvements to the sync methods for later release

for the time being, we have provided a bootstrap (for a full verification import) and a pre-processed chaindata file which can be dropped into your daemon to allow you to get to full height in minutes rather than days. however we always recommend a full verify from block 0 to ensure your on-disk blockchain is valid and this can several days on a slow CPU (such as the vCPUs which are commonly used for hosting wallets on a VPS)

please keep an eye open for our sync updates in the sync branch

**Comment by carsenk** [comment]
I will leave this open since it is something we are addressing in the sync branch.

**Comment by inliquid** [comment]
The problem is not in speed itself. Though it slow, now it syncing nearly the same time as Bitcoin full node from 0 block of 2009, Litecoin full node syncing 3x times faster than Denarius atm. It's non-sense. 

However, I think I described the case quite well in my first message. The problem is not in speed, but in the fact that since Denarius 2.0 speed of synchronization has decreased by a number of times.

In my case (same network, same equipment, same OS, everything, few days difference):
- v1.0.7 full sync from block 0 to block 600k+ -> **~5-6 hours**
- v2.0 full sync from block 0 to block 600k+ -> **~50 hours**

Everyone can easily reproduce this test by 
1. Cleaning _data dir_ contents, running v1.0.7 for a couple of hours, then making screenshot or writing down the progress.
2. Cleaning _data dir_ contents, replacing v1.0.7 with 2.0 binary (f.e. *.exe) and repeating the run.
3. Comparing results.

**Comment by enkayz** [comment]
this issue should be addressed in v2.5 release which should be available for testnet soon

**Comment by carsenk** [comment]
This was fixed in the v2.5 release to be improved from around 3 blocks per second to upwards of 100-400 blocks per second. This still will more than likely be improved and worked even more in the future, to get even faster speeds. Closing issue now :)
